BaseURL: ""
LanguageCode: "en-us"
title: "Hello. I'm Dean Clatworthy"
tagline:
uglyURLs: "true"
theme: dean
summaryLength: 25

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tokyonight-day

disableKinds: ["taxonomy"]

Params:
  SiteName: DeanClatworthy.com
  TitleSuffix: Dean Clatworthy | Web Developer
  Tagline: "I build web services for a living. <code>Full-stack</code>, <code>Cloud</code>, <code>Databases</code>"
  Author:
    Name: Dean Clatworthy
  Homepage:
    Intro: |
      Greetings! I'm originally from England ğŸ´ó §ó ¢ó ¥ó ®ó §ó ¿ but now I live in Helsinki, Finland ğŸ‡«ğŸ‡®. I've a BSc. in Computer Science
      and I've been building things with computers now for as long as I can remember. I particularly enjoy building web applications -
      and I specialise in both back-end and front-end web application development in the cloud.
      I have a <a rel="noopener" target="_blank" href="https://github.com/deanc">Github profile</a>, where you can see some of my code. You can also reach me on
      <a rel="noopener" target="_blank" href="https://twitter.com/deanclatworthy">Twitter</a>, or fill in the <a href="/contact.html">contact form</a> and I'll try
      to mail you back.
  Comments:
    disqus:
      shortcode: "deanclatworthy"

permalinks:
  post: /:year/:month/:day/:slug/

menu:
  main:
      - Name: "Home"
        Pre: "<i class='fa fa-heart'></i>"
        Weight: 1
        Identifier: "home"
        URL: "/"

services:
  disqus:
    shortname: deanclatworthy